# Generated by Django 5.1.3 on 2025-02-02 11:21

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_appointment_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
